### PR TITLE
Added logic for users in zip codes with split congressional districts

### PR DESCRIPTION
**Pull request by cdoremus**
Logic added for users in zip codes with split congressional districts. 

Other things done in this PR:
* Used Trans from `i18n-next` to interpolate i18n message resources containing links
* Fixed build-css script in `package.json` using `rimraf`
* Changed `LocationActionType` to string-based enum to allow code completion in editor
* Fixed a lot of merge conflicts that occured when I rebased to PR #30 

Please run `yarn` to add new dependency `rimraf` and automatically re-run the build-css script.

This PR is a partial implementation of issue #10

### CODE REVIEW

**Comment by nickoneill** [comment]
Does this need to be rebased? Seems like a lot of earlier commits unrelated to the split stuff

**Comment by cdoremus** [comment]
@nickoneill I'll try rebasing to get rid of the old commits.

BTW, What is the best way to test tweaks to CircleCi builds without having to keep pushing possible fixes to this PR? I know what's braking the CircleCi build and I want to try some things out rather than just rolling back changes to the build-css script in `package.json`.

**Comment by nickoneill** [comment]
@cdoremus do you have access to the "rebuild" button in the top right on this page: https://circleci.com/gh/5calls/react-dev/34

You probably need to login with github before it's available

**Comment by nickoneill** [comment]
Like testing local changes on CircleCI? I'm not entirely sure what's easy... you could make edits in the github editor to kick off a new build without going through a full push if that makes sense?

**Comment by cdoremus** [comment]
@nickoneill I'll worry about fixing the build later. Right now, I'm being sucked down a rebase black hole! :upside_down_face: I'll try to ping you later on Slack to get some help with rebasing, but my availability for the rest of the day is limited.

**Comment by nickoneill** [comment]
Sorry for the hassle! Ping me whenever you're free and I can help

**Comment by cdoremus** [comment]
This has been replaced by PR #33

**Pull request closed without merging**
