### PR TITLE
Route by id with reorg to top-level redux containers

### PR DESCRIPTION
**Pull request by schraj**
This is not yet working.  I'm putting it up for discussion and for some typescript guidance on getting the CallPageContainer connect call to work with CallPage.

The work in this PR is to implement issue #3 and #4 in addition to improving the app's architecture.

### CODE REVIEW

**Comment by schraj** [comment]
looks like this is now working.  Done page is working too.

**Comment by schraj** [comment]
I still have to make it grab the issues from api if they are not there(page has been refreshed or gone straight to a route with an id)

**Comment by schraj** [comment]
I've added the loading of issues if you go straight to the url

**Comment by schraj** [comment]
I added in redux-persist to this since it already has all my other changes.  It is currently only persisting the locationState key from the store.

**Comment by cdoremus** [comment]
I just added some TypeScript magic to help make the use of `redux-persist` more type safe (commit 101e53a). This involved using TS `keyof` operator and mapped types. See code comments for more details.

**Pull request merged**
