### PR TITLE
Fixed privacy.html styling

### PR DESCRIPTION
**Pull request by cdoremus**
Fixes issue #41

### CODE REVIEW

**Comment by nickoneill** [comment]
Seems like the old privacy was pointing at the normal css file location - why didn't that work? What does copying it get us?

**Comment by cdoremus** [comment]
@nickoneill  copying is the simplest way to do the `privacy.html` styling. The other alternatives are:
1. Copy the individual styles in `bundle.css` that the `privacy.html` uses into a `<style>` element in `privacy.html`.
2. Figure out how to get webpack to automatically inject the styles (this could take some time).

I've done number 1. Do you want me to push that here?

**Comment by nickoneill** [comment]
I guess I'm confused how styles get into the normal react pages in the first place. `index.html` still links `style.css` - are they injected and this link isn't used?

**Comment by cdoremus** [comment]
@nickoneill it's Webpack magic (or voodoo) that converts the SCSS into CSS and bundles it up into a file with an obfuscated name. The JavaScript is also bundled with an obfuscated file name to make sure any new deployments are served (and not pulled from the cache). Webpack also rebuilds `index.html` to compress it and inject the new CSS and JavaScript file names into the appropriate `<link>` and `<script>` elements. This all happens in memory with the Webpack development server. Run `yarn build` too see how it works in practice.

Option 2 that I proposed above would try to apply the same Webpack magic to `privacy.html`.

**Comment by nickoneill** [comment]
OK, I see it in the built version.

Option 1 is good for `privacy.html` page, let's keep it simple for now.

Other question: web pack builds and bundles a static, zero-byte `styles.css` file in a css folder. `index.html` links this styles file in. Can we remove this entirely?

**Comment by cdoremus** [comment]
@nickoneill Option 1 pushed in commit d98dcee. The `style.css` file was removed in a previous commit (5a2a772) and its reference in `index.html` has been deleted in commit 5b6954a.

**Review by nickoneill — APPROVED** [review]

**Pull request merged**
