### PR TITLE
Adds Localization(i18Next/React-i18Next) and implements it in HomePage Component Hierarchy

### PR DESCRIPTION
**Pull request by schraj**
This library combination is pretty sweet.  The typescript worked perfectly.  We can use the same formatted translation files that we have in the Choo app.  And, there was much less head scratching trying to get it to work than with Choo : )  Handles the initial implemenation for Issue #6. 

There will still need to be an effort to go through the whole site and make the changes to the translations.

### CODE REVIEW

**Comment by schraj** [comment]
I went ahead and did the translation for the whole site.

**Comment by cdoremus** [comment]
Jeremy, good job on pulling this off so quickly! 

I pulled the `loc` branch and a number of the unit tests are failing. These should be fixed.

**Comment by schraj** [comment]
oh yeah, forgot those got in there. I'll fix them.

**Comment by nickoneill** [comment]
Try pushing this again if you want circle to run the tests, I had to flip a setting to build forks

**Comment by schraj** [comment]
NOTE: This is not now ready to review.  I'm struggling to get the tests working with the i18next library.  I can close the request or just leave it here as I struggle with it for a bit. : <{}.  Let me know what is preferred.

**Pull request closed without merging**
